### ISSUE TITLE
`requirments.txt`

### ISSUE THREAD

**Issue by enryH** [RasmussenLab/MOVE#13]
Is the `requirements.txt` still used?

**Comment by ri-heme** [comment]
From the [Python documentation](https://packaging.python.org/en/latest/discussions/install-requires-vs-requirements/#requirements-files):

> Whereas `install_requires` (i.e. setup.py) defines the dependencies for a single project, [Requirements Files](https://pip.pypa.io/en/latest/user_guide/#requirements-files) are often used to define the requirements for a complete Python environment.
> Whereas `install_requires` requirements are minimal, requirements files often contain an exhaustive listing of pinned versions for the purpose of achieving [repeatable installations](https://pip.pypa.io/en/latest/user_guide/#repeatability) of a complete environment.

So my idea was using the `requirements.txt` to keep track of exact versions of the dependencies (for instance, the same as in the DIRECT server), and `setup.cfg` to just list dependency names. However, `requirements.txt` has been updated.

**Comment by enryH** [comment]
that sounds reasonable. 

By the way: I installed it within a conda environment using pip - and so far i had no errors.
