### ISSUE TITLE
Rename 05_identify_drug_assosiation

### ISSUE THREAD

**Issue by simonrasmu** [RasmussenLab/MOVE#17]
Rename 05_identify_drug_assosiation to 05_identify_drug_association

**Comment by enryH** [comment]
Naming a module with numbers is a bit tricky, as this result in an invalid identifier for the module when imported: Valid identifiers are "the uppercase and lowercase letters A through Z, the underscore _ and, except for the first character, the digits 0 through 9." ([ref](https://docs.python.org/3/reference/lexical_analysis.html#identifiers))

It is probably not really important as there is nothing except execution scripts in the numbered folders, but I just wanted to give you the hint!

**Comment by simonrasmu** [comment]
I am all for remove the 0X infront of the modules.
