### ISSUE TITLE
🎨 Format docstrings

### ISSUE THREAD

**Issue by ri-heme** [RasmussenLab/MOVE#31]
For compatibility with Sphinx (and better annotation), we will format the docstrings according to Google style guide.

Relevant resources:
- [Style Guide](https://google.github.io/styleguide/pyguide.html#38-comments-and-docstrings)
- [Examples](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html)

**Comment by enryH** [comment]
which ones do you use now? Do you have a reference for the compatibility? (I used the numpy format so far as the default).

**Comment by ri-heme** [comment]
Sphinx's [Napoleon extension](https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html) supports Google style docstrings. Currently, the docstrings don't adhere to any specific convention. They resemble the Google style though, so it should be easy to change.
