### ISSUE TITLE
NA class is created even without NA in categorical data

### ISSUE THREAD

**Issue by mpielies** [RasmussenLab/MOVE#35]
César and I are applying MOVE to a new dataset. 
For the categorical data, we are having issues with the function encode_cat(). We realized the following:

Not an issue:
1) The class NA (0,...,0) is added even though there are no NAs. 

Issues:
2) The function np.isnan(), which is used to check if the array with unique classes contains a NaN class, does not work if the class numbers are introduced as strings. (TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe'')
3) If one class is not represented in the data of a new user ( no  patient of class 3,e.g., in a class 1-9 setting), the one-hot encoding is rearranged. This leads to the creation of keys 1-8 plus the nan key with the vector (0...0) assigned. This induces problems at the end of the function, when calling e.g. encodings[lab] for a patient belonging to class 9 (lab=9): the key 9 does not exist anymore in the encodings dict.

Thanks!

**Comment by ri-heme** [comment]
Hi Marc, could you share/link the dataset that you were using when you came across this issue?

**Comment by mpielies** [comment]
Hi! This is the dataset. https://www.kaggle.com/datasets/zzettrkalpakbal/full-filled-brain-stroke-dataset .
This issue would happen to anyone binning data into classes ( Maybe data in ranges 10-20, 20-30 e.g.) when one class is not being represented in the data.
