### ISSUE TITLE
QoL changes

### ISSUE THREAD

**Issue by ri-heme** [RasmussenLab/MOVE#53]
The following is a list of low-priority changes to do to MOVE:

- [x] #39 
- [x] Rename `processed_data_path` in config to `results_path`
- [x] Add type hints to methods in `vae.py` module

**Comment by valentas1** [comment]
Solved them:
1) 5167e59 
2) 05b8bf9
3) c59878d

**Comment by ri-heme** [comment]
Perfect, thanks Valentas!
