### ISSUE TITLE
Issue of "move-dl"cannot be found after I installed "MOVE" successfully.

### ISSUE THREAD

**Issue by Oliver2025** [RasmussenLab/MOVE#85]
Dear Sir,
I encountered an issue at a certain step below, where the terminal responded with an error message stating that it could not find "move-dl". I would be immensely grateful if you could provide some guidance or solutions to rectify this issue.
From here:
on the parent directory of the config folder (in this example, it is the tutorial folder), and proceed to run:
>>> cd tutorial
>>> move-dl data=random_small task=encode_data — **_Cannot find move-dl_**

Your help would significantly contribute to my understanding and application of your work. I appreciate your time in advance.

**Comment by ri-heme** [comment]
Hi Oliver. I would need more details in order to reproduce this error and help you out. Are you running MOVE from an environment? Can you confirm the installation was successful by importing MOVE in a Python script? (e.g., `import move; print(move.__version__)`)

**Comment by Oliver2025** [comment]
Hi Ri-heme, I did what you said and get the results below: 

<img width="533" alt="截屏2023-06-29 10 38 02" src="https://github.com/RasmussenLab/MOVE/assets/70757048/5d62db52-a00d-4dfb-898f-13f922c017ac">

The installation was successful. Could you please help me to check the error? Thank you in advance.

**Comment by ri-heme** [comment]
I would first recommend to install the latest version of MOVE (currently, v.1.4.9), and then you could try if the following command works: `move-dl --help`.

**Comment by Oliver2025** [comment]
Thank you so much for your help! We solved the problem and can run "MOVE" now.

**Comment by ri-heme** [comment]
Great to hear! Let us know if there's any other hiccup
