### ISSUE TITLE
About the perturbation

### ISSUE THREAD

**Issue by SZ-qing** [RasmussenLab/MOVE#86]
Hello, I saw in your article that samples that have received drug treatment will be eliminated when perturbing. What I want to ask is if I use the move tool to disturb, do I need to take the sample that received a certain drug by myself? Remove it, or the current code will automatically remove it for me.
Thanks.

**Comment by ri-heme** [comment]
Hi there. Those samples will be removed automatically. So if your dataset has 400 samples (205 control, 195 under treatment) and you make the perturbation "control ➡️ treatment," then the 195 treatment samples will be "removed" during the associations step.

**Comment by SZ-qing** [comment]
Thanks


---- Replied Message ----
| From | Ricardo Hernández ***@***.***> |
| Date | 07/14/2023 19:16 |
| To | RasmussenLab/MOVE ***@***.***> |
| Cc | SZ-qing ***@***.***>,
Author ***@***.***> |
| Subject | Re: [RasmussenLab/MOVE] About the perturbation (Issue #86) |

Hi there. Those samples will be removed automatically. So if your dataset has 400 samples (205 control, 195 under treatment) and you make the perturbation "control ➡️ treatment," then the 195 treatment samples will be "removed" during the associations step.
